on: push
jobs:
  run-node-app:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - run: actions/checkout@v3
      - run: npm install
      - run: node app.js